name: CI/CD Pipeline that triggers terraform and ansible operations.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials setting up AWS account to access infrastructure resources
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "eu-west-1" # ireland

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.0 # Use the latest stable version or the specific version you need

      - name: Terraform init
        run: terraform init
        working-directory: ./terraform

      - name: print ssh public key
        run: echo ${{ secrets.AWS_SSH_PUBLIC_KEY }}

      - name: Planning terraform script
        run: terraform plan -var="ssh_public_key=${{ secrets.AWS_SSH_PUBLIC_KEY }}"
        working-directory: ./terraform

      - name: Running terrafrom script
        run: terraform apply -auto-approve
        working-directory: ./terraform

  ansible:
    name: "Ansible"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key for Ansible
        run: |
          mkdir -p ~/.ssh  # Create the directory if it doesn't exist
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Map the GitHub secret to the id_rsa file
          chmod 00 ~/.ssh/id_rsa  # Secure the private key file

      - name: Docker setup
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.P_DOCKER_USERNAME }} # GitHub Secret for Docker Hub username
          password: ${{ secrets.P_DOCKER_PASSWORD }} # GitHub Secret for Docker Hub password or token

      - name: Docker Build
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.P_DOCKER_USERNAME }}/avinash:latest --push ./app/Dockerfile

      - name: Run Ansible Playbook
        run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ansible-setup/inventory.ini ansible-setup/install-docker.yml
